// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};

/**
 * AuthResponse
 */
export type AuthResponse = {
    /**
     * Accesstoken
     */
    accessToken: string;
    /**
     * Refreshtoken
     */
    refreshToken: string;
    user: UserRead;
};

/**
 * Body_login_user_api_v1_login__post
 */
export type BodyLoginUserApiV1LoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * BuildingCreate
 */
export type BuildingCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address: string;
};

/**
 * BuildingRead
 */
export type BuildingRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address: string;
    /**
     * Id
     */
    id: number;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
};

/**
 * BuildingUpdate
 */
export type BuildingUpdate = {
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address: string;
};

/**
 * GroupCreate
 */
export type GroupCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Course
     */
    course: number;
    /**
     * Institute
     */
    institute: string;
};

/**
 * GroupRead
 */
export type GroupRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Course
     */
    course: number;
    /**
     * Institute
     */
    institute: string;
    /**
     * Id
     */
    id: number;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
};

/**
 * GroupSummary
 */
export type GroupSummary = {
    /**
     * Name
     */
    name: string;
    /**
     * Course
     */
    course: number;
    /**
     * Institute
     */
    institute: string;
    /**
     * Id
     */
    id: number;
    /**
     * Countstudents
     */
    countStudents: number;
};

/**
 * GroupUpdate
 */
export type GroupUpdate = {
    /**
     * Name
     */
    name: string;
    /**
     * Course
     */
    course: number;
    /**
     * Institute
     */
    institute: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LessonById
 */
export type LessonById = {
    /**
     * Id
     */
    id: number;
    /**
     * Timeid
     */
    timeId: number;
    /**
     * Dayofweek
     */
    dayOfWeek: number;
    /**
     * Type
     */
    type: string;
    group: GroupRead;
    subject: SubjectRead;
    teacher: TeacherRead;
    room: RoomReadMinimal;
};

/**
 * LessonCreate
 */
export type LessonCreate = {
    /**
     * Timeid
     */
    timeId: number;
    /**
     * Dayofweek
     */
    dayOfWeek: number;
    /**
     * Type
     */
    type: string;
    /**
     * Subjectid
     */
    subjectId: number;
    /**
     * Teacherid
     */
    teacherId: number;
    /**
     * Roomid
     */
    roomId: number;
    /**
     * Groupid
     */
    groupId: number;
};

/**
 * LessonReadMinimal
 */
export type LessonReadMinimal = {
    /**
     * Timeid
     */
    timeId: number;
    /**
     * Dayofweek
     */
    dayOfWeek: number;
    /**
     * Type
     */
    type: string;
    /**
     * Id
     */
    id: number;
    /**
     * Subjectid
     */
    subjectId: number;
    /**
     * Teacherid
     */
    teacherId: number;
    /**
     * Roomid
     */
    roomId: number;
    /**
     * Groupid
     */
    groupId: number;
};

/**
 * LessonUpdate
 */
export type LessonUpdate = {
    /**
     * Timeid
     */
    timeId: number;
    /**
     * Dayofweek
     */
    dayOfWeek: number;
    /**
     * Type
     */
    type: string;
    /**
     * Subjectid
     */
    subjectId: number;
    /**
     * Teacherid
     */
    teacherId: number;
    /**
     * Roomid
     */
    roomId: number;
    /**
     * Groupid
     */
    groupId: number;
};

/**
 * PasswordChange
 */
export type PasswordChange = {
    /**
     * Newpassword
     */
    newPassword: string;
};

/**
 * RoomCreate
 */
export type RoomCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Floor
     */
    floor: number;
    /**
     * Capacity
     */
    capacity: number;
    /**
     * Status
     *
     * 0 - Not available, 1 - Available
     */
    status: number;
    /**
     * Buildingid
     */
    buildingId: number;
};

/**
 * RoomRead
 */
export type RoomRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Floor
     */
    floor: number;
    /**
     * Capacity
     */
    capacity: number;
    /**
     * Status
     *
     * 0 - Not available, 1 - Available
     */
    status: number;
    /**
     * Buildingid
     */
    buildingId: number;
    /**
     * Id
     */
    id: number;
    building: BuildingRead;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
};

/**
 * RoomReadMinimal
 */
export type RoomReadMinimal = {
    /**
     * Name
     */
    name: string;
    /**
     * Floor
     */
    floor: number;
    /**
     * Capacity
     */
    capacity: number;
    /**
     * Status
     *
     * 0 - Not available, 1 - Available
     */
    status: number;
    /**
     * Buildingid
     */
    buildingId: number;
    /**
     * Id
     */
    id: number;
};

/**
 * RoomUpdate
 */
export type RoomUpdate = {
    /**
     * Name
     */
    name: string;
    /**
     * Floor
     */
    floor: number;
    /**
     * Capacity
     */
    capacity: number;
    /**
     * Status
     *
     * 0 - Not available, 1 - Available
     */
    status: number;
    /**
     * Buildingid
     */
    buildingId: number;
};

/**
 * StudentCreate
 */
export type StudentCreate = {
    /**
     * Firstname
     */
    firstName: string;
    /**
     * Lastname
     */
    lastName: string;
    /**
     * Middlename
     */
    middleName: string;
    /**
     * Dateofbirth
     */
    dateOfBirth: string;
    /**
     * Email
     */
    email: string;
    /**
     * Phone
     */
    phone: string;
    /**
     * Course
     */
    course: number;
    /**
     * Groupid
     */
    groupId: number;
};

/**
 * StudentRead
 */
export type StudentRead = {
    /**
     * Firstname
     */
    firstName: string;
    /**
     * Lastname
     */
    lastName: string;
    /**
     * Middlename
     */
    middleName: string;
    /**
     * Dateofbirth
     */
    dateOfBirth: string;
    /**
     * Email
     */
    email: string;
    /**
     * Phone
     */
    phone: string;
    /**
     * Course
     */
    course: number;
    /**
     * Groupid
     */
    groupId: number;
    /**
     * Id
     */
    id: number;
    /**
     * Fullname
     */
    fullName: string;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
};

/**
 * StudentUpdate
 */
export type StudentUpdate = {
    /**
     * Firstname
     */
    firstName: string;
    /**
     * Lastname
     */
    lastName: string;
    /**
     * Middlename
     */
    middleName: string;
    /**
     * Dateofbirth
     */
    dateOfBirth: string;
    /**
     * Email
     */
    email: string;
    /**
     * Phone
     */
    phone: string;
    /**
     * Course
     */
    course: number;
    /**
     * Groupid
     */
    groupId: number;
};

/**
 * SubjectCreate
 */
export type SubjectCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Semester
     */
    semester: number;
    /**
     * Totalhours
     */
    totalHours: number;
    /**
     * Isoptional
     */
    isOptional: boolean;
};

/**
 * SubjectRead
 */
export type SubjectRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Semester
     */
    semester: number;
    /**
     * Totalhours
     */
    totalHours: number;
    /**
     * Isoptional
     */
    isOptional: boolean;
    /**
     * Id
     */
    id: number;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
};

/**
 * SubjectUpdate
 */
export type SubjectUpdate = {
    /**
     * Name
     */
    name: string;
    /**
     * Semester
     */
    semester: number;
    /**
     * Totalhours
     */
    totalHours: number;
    /**
     * Isoptional
     */
    isOptional: boolean;
};

/**
 * TeacherCreate
 */
export type TeacherCreate = {
    /**
     * Firstname
     */
    firstName: string;
    /**
     * Middlename
     */
    middleName: string | null;
    /**
     * Lastname
     */
    lastName: string;
    /**
     * Email
     */
    email: string | null;
    /**
     * Phone
     */
    phone: string | null;
    /**
     * Department
     */
    department: string;
    /**
     * Title
     */
    title: string;
};

/**
 * TeacherRead
 */
export type TeacherRead = {
    /**
     * Firstname
     */
    firstName: string;
    /**
     * Middlename
     */
    middleName: string | null;
    /**
     * Lastname
     */
    lastName: string;
    /**
     * Email
     */
    email: string | null;
    /**
     * Phone
     */
    phone: string | null;
    /**
     * Department
     */
    department: string;
    /**
     * Title
     */
    title: string;
    /**
     * Id
     */
    id: number;
    /**
     * Fullname
     */
    fullName: string;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
};

/**
 * TeacherUpdate
 */
export type TeacherUpdate = {
    /**
     * Firstname
     */
    firstName: string;
    /**
     * Middlename
     */
    middleName: string | null;
    /**
     * Lastname
     */
    lastName: string;
    /**
     * Email
     */
    email: string | null;
    /**
     * Phone
     */
    phone: string | null;
    /**
     * Department
     */
    department: string;
    /**
     * Title
     */
    title: string;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: string;
    /**
     * Role
     */
    role: string;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Role
     */
    role?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type RegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/register/';
};

export type RegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserError = RegisterUserErrors[keyof RegisterUserErrors];

export type RegisterUserResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type DebugCookiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/debug/cookies';
};

export type DebugCookiesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoginUserData = {
    body: BodyLoginUserApiV1LoginPost;
    path?: never;
    query?: never;
    url: '/api/v1/login/';
};

export type LoginUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginUserError = LoginUserErrors[keyof LoginUserErrors];

export type LoginUserResponses = {
    /**
     * Successful Response
     */
    200: AuthResponse;
};

export type LoginUserResponse = LoginUserResponses[keyof LoginUserResponses];

export type LogoutUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/logout/';
};

export type LogoutUserResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChangePasswordData = {
    body: PasswordChange;
    path?: never;
    query?: never;
    url: '/api/v1/change-password/';
};

export type ChangePasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type GetAllUsersResponses = {
    /**
     * Response Get All Users Api V1 Users  Get
     *
     * Successful Response
     */
    200: Array<UserRead>;
};

export type GetAllUsersResponse = GetAllUsersResponses[keyof GetAllUsersResponses];

export type CheckAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/check/';
};

export type CheckAuthResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type CheckAuthResponse = CheckAuthResponses[keyof CheckAuthResponses];

export type ProcessRefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/refresh/';
};

export type ProcessRefreshTokenResponses = {
    /**
     * Successful Response
     */
    200: AuthResponse;
};

export type ProcessRefreshTokenResponse = ProcessRefreshTokenResponses[keyof ProcessRefreshTokenResponses];

export type GetAllBuildingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/building/';
};

export type GetAllBuildingsResponses = {
    /**
     * Response Get All Buildings Api V1 Building  Get
     *
     * Successful Response
     */
    200: Array<BuildingRead>;
};

export type GetAllBuildingsResponse = GetAllBuildingsResponses[keyof GetAllBuildingsResponses];

export type CreateBuildingData = {
    body: BuildingCreate;
    path?: never;
    query?: never;
    url: '/api/v1/building/';
};

export type CreateBuildingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateBuildingError = CreateBuildingErrors[keyof CreateBuildingErrors];

export type CreateBuildingResponses = {
    /**
     * Successful Response
     */
    201: BuildingRead;
};

export type CreateBuildingResponse = CreateBuildingResponses[keyof CreateBuildingResponses];

export type DeleteBuildingData = {
    body?: never;
    path: {
        /**
         * Building Id
         */
        building_id: number;
    };
    query?: never;
    url: '/api/v1/building/{building_id}';
};

export type DeleteBuildingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteBuildingError = DeleteBuildingErrors[keyof DeleteBuildingErrors];

export type DeleteBuildingResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteBuildingResponse = DeleteBuildingResponses[keyof DeleteBuildingResponses];

export type GetBuildingByIdData = {
    body?: never;
    path: {
        /**
         * Building Id
         */
        building_id: number;
    };
    query?: never;
    url: '/api/v1/building/{building_id}';
};

export type GetBuildingByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBuildingByIdError = GetBuildingByIdErrors[keyof GetBuildingByIdErrors];

export type GetBuildingByIdResponses = {
    /**
     * Successful Response
     */
    200: BuildingRead;
};

export type GetBuildingByIdResponse = GetBuildingByIdResponses[keyof GetBuildingByIdResponses];

export type UpdateBuildingData = {
    body: BuildingUpdate;
    path: {
        /**
         * Building Id
         */
        building_id: number;
    };
    query?: never;
    url: '/api/v1/building/{building_id}';
};

export type UpdateBuildingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateBuildingError = UpdateBuildingErrors[keyof UpdateBuildingErrors];

export type UpdateBuildingResponses = {
    /**
     * Successful Response
     */
    200: BuildingRead;
};

export type UpdateBuildingResponse = UpdateBuildingResponses[keyof UpdateBuildingResponses];

export type SearchGroupsByNameData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Query
         */
        query: unknown;
    };
    url: '/api/v1/group/search';
};

export type SearchGroupsByNameErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchGroupsByNameError = SearchGroupsByNameErrors[keyof SearchGroupsByNameErrors];

export type SearchGroupsByNameResponses = {
    /**
     * Response Search Groups By Name Api V1 Group Search Get
     *
     * Successful Response
     */
    200: Array<GroupRead>;
};

export type SearchGroupsByNameResponse = SearchGroupsByNameResponses[keyof SearchGroupsByNameResponses];

export type GetGroupsSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/group/summary/';
};

export type GetGroupsSummaryResponses = {
    /**
     * Response Get Groups Summary Api V1 Group Summary  Get
     *
     * Successful Response
     */
    200: Array<GroupSummary>;
};

export type GetGroupsSummaryResponse = GetGroupsSummaryResponses[keyof GetGroupsSummaryResponses];

export type GetAllGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/group/';
};

export type GetAllGroupsResponses = {
    /**
     * Response Get All Groups Api V1 Group  Get
     *
     * Successful Response
     */
    200: Array<GroupRead>;
};

export type GetAllGroupsResponse = GetAllGroupsResponses[keyof GetAllGroupsResponses];

export type CreateGroupData = {
    body: GroupCreate;
    path?: never;
    query?: never;
    url: '/api/v1/group/';
};

export type CreateGroupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateGroupError = CreateGroupErrors[keyof CreateGroupErrors];

export type CreateGroupResponses = {
    /**
     * Successful Response
     */
    201: GroupRead;
};

export type CreateGroupResponse = CreateGroupResponses[keyof CreateGroupResponses];

export type DeleteGroupData = {
    body?: never;
    path: {
        /**
         * Group Id
         */
        group_id: number;
    };
    query?: never;
    url: '/api/v1/group/{group_id}';
};

export type DeleteGroupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteGroupError = DeleteGroupErrors[keyof DeleteGroupErrors];

export type DeleteGroupResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteGroupResponse = DeleteGroupResponses[keyof DeleteGroupResponses];

export type GetGroupByIdData = {
    body?: never;
    path: {
        /**
         * Group Id
         */
        group_id: number;
    };
    query?: never;
    url: '/api/v1/group/{group_id}';
};

export type GetGroupByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGroupByIdError = GetGroupByIdErrors[keyof GetGroupByIdErrors];

export type GetGroupByIdResponses = {
    /**
     * Successful Response
     */
    200: GroupRead;
};

export type GetGroupByIdResponse = GetGroupByIdResponses[keyof GetGroupByIdResponses];

export type UpdateGroupData = {
    body: GroupUpdate;
    path: {
        /**
         * Group Id
         */
        group_id: number;
    };
    query?: never;
    url: '/api/v1/group/{group_id}';
};

export type UpdateGroupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateGroupError = UpdateGroupErrors[keyof UpdateGroupErrors];

export type UpdateGroupResponses = {
    /**
     * Successful Response
     */
    200: GroupRead;
};

export type UpdateGroupResponse = UpdateGroupResponses[keyof UpdateGroupResponses];

export type GetLessonsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Group
         */
        group?: number | null;
        /**
         * Teacher
         */
        teacher?: number | null;
        /**
         * Room
         */
        room?: number | null;
    };
    url: '/api/v1/lesson/';
};

export type GetLessonsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLessonsError = GetLessonsErrors[keyof GetLessonsErrors];

export type GetLessonsResponses = {
    /**
     * Response Get Lessons Api V1 Lesson  Get
     *
     * Successful Response
     */
    200: Array<LessonById>;
};

export type GetLessonsResponse = GetLessonsResponses[keyof GetLessonsResponses];

export type CreateLessonData = {
    body: LessonCreate;
    path?: never;
    query?: never;
    url: '/api/v1/lesson/';
};

export type CreateLessonErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateLessonError = CreateLessonErrors[keyof CreateLessonErrors];

export type CreateLessonResponses = {
    /**
     * Successful Response
     */
    201: LessonReadMinimal;
};

export type CreateLessonResponse = CreateLessonResponses[keyof CreateLessonResponses];

export type DeleteLessonData = {
    body?: never;
    path: {
        /**
         * Lesson Id
         */
        lesson_id: number;
    };
    query?: never;
    url: '/api/v1/lesson/{lesson_id}';
};

export type DeleteLessonErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteLessonError = DeleteLessonErrors[keyof DeleteLessonErrors];

export type DeleteLessonResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteLessonResponse = DeleteLessonResponses[keyof DeleteLessonResponses];

export type UpdateLessonData = {
    body: LessonUpdate;
    path: {
        /**
         * Lesson Id
         */
        lesson_id: number;
    };
    query?: never;
    url: '/api/v1/lesson/{lesson_id}';
};

export type UpdateLessonErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateLessonError = UpdateLessonErrors[keyof UpdateLessonErrors];

export type UpdateLessonResponses = {
    /**
     * Successful Response
     */
    200: LessonReadMinimal;
};

export type UpdateLessonResponse = UpdateLessonResponses[keyof UpdateLessonResponses];

export type SearchRoomsByNameData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Query
         */
        query: unknown;
    };
    url: '/api/v1/room/search';
};

export type SearchRoomsByNameErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchRoomsByNameError = SearchRoomsByNameErrors[keyof SearchRoomsByNameErrors];

export type SearchRoomsByNameResponses = {
    /**
     * Response Search Rooms By Name Api V1 Room Search Get
     *
     * Successful Response
     */
    200: Array<RoomReadMinimal>;
};

export type SearchRoomsByNameResponse = SearchRoomsByNameResponses[keyof SearchRoomsByNameResponses];

export type GetAllRoomsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/room/';
};

export type GetAllRoomsResponses = {
    /**
     * Response Get All Rooms Api V1 Room  Get
     *
     * Successful Response
     */
    200: Array<RoomRead>;
};

export type GetAllRoomsResponse = GetAllRoomsResponses[keyof GetAllRoomsResponses];

export type CreateRoomData = {
    body: RoomCreate;
    path?: never;
    query?: never;
    url: '/api/v1/room/';
};

export type CreateRoomErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRoomError = CreateRoomErrors[keyof CreateRoomErrors];

export type CreateRoomResponses = {
    /**
     * Successful Response
     */
    201: RoomReadMinimal;
};

export type CreateRoomResponse = CreateRoomResponses[keyof CreateRoomResponses];

export type DeleteRoomData = {
    body?: never;
    path: {
        /**
         * Room Id
         */
        room_id: number;
    };
    query?: never;
    url: '/api/v1/room/{room_id}';
};

export type DeleteRoomErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRoomError = DeleteRoomErrors[keyof DeleteRoomErrors];

export type DeleteRoomResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteRoomResponse = DeleteRoomResponses[keyof DeleteRoomResponses];

export type GetRoomByIdData = {
    body?: never;
    path: {
        /**
         * Room Id
         */
        room_id: number;
    };
    query?: never;
    url: '/api/v1/room/{room_id}';
};

export type GetRoomByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRoomByIdError = GetRoomByIdErrors[keyof GetRoomByIdErrors];

export type GetRoomByIdResponses = {
    /**
     * Successful Response
     */
    200: RoomRead;
};

export type GetRoomByIdResponse = GetRoomByIdResponses[keyof GetRoomByIdResponses];

export type UpdateRoomData = {
    body: RoomUpdate;
    path: {
        /**
         * Room Id
         */
        room_id: number;
    };
    query?: never;
    url: '/api/v1/room/{room_id}';
};

export type UpdateRoomErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRoomError = UpdateRoomErrors[keyof UpdateRoomErrors];

export type UpdateRoomResponses = {
    /**
     * Successful Response
     */
    200: RoomReadMinimal;
};

export type UpdateRoomResponse = UpdateRoomResponses[keyof UpdateRoomResponses];

export type DeleteStudentData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Student Id
         */
        student_id: number;
    };
    url: '/api/v1/student/';
};

export type DeleteStudentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteStudentError = DeleteStudentErrors[keyof DeleteStudentErrors];

export type DeleteStudentResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteStudentResponse = DeleteStudentResponses[keyof DeleteStudentResponses];

export type GetAllStudentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/student/';
};

export type GetAllStudentsResponses = {
    /**
     * Response Get All Students Api V1 Student  Get
     *
     * Successful Response
     */
    200: Array<StudentRead>;
};

export type GetAllStudentsResponse = GetAllStudentsResponses[keyof GetAllStudentsResponses];

export type CreateStudentData = {
    body: StudentCreate;
    path?: never;
    query?: never;
    url: '/api/v1/student/';
};

export type CreateStudentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateStudentError = CreateStudentErrors[keyof CreateStudentErrors];

export type CreateStudentResponses = {
    /**
     * Successful Response
     */
    201: StudentRead;
};

export type CreateStudentResponse = CreateStudentResponses[keyof CreateStudentResponses];

export type GetStudentByIdData = {
    body?: never;
    path: {
        /**
         * Student Id
         */
        student_id: number;
    };
    query?: never;
    url: '/api/v1/student/{student_id}';
};

export type GetStudentByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStudentByIdError = GetStudentByIdErrors[keyof GetStudentByIdErrors];

export type GetStudentByIdResponses = {
    /**
     * Successful Response
     */
    200: StudentRead;
};

export type GetStudentByIdResponse = GetStudentByIdResponses[keyof GetStudentByIdResponses];

export type UpdateStudentData = {
    body: StudentUpdate;
    path: {
        /**
         * Student Id
         */
        student_id: number;
    };
    query?: never;
    url: '/api/v1/student/{student_id}';
};

export type UpdateStudentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateStudentError = UpdateStudentErrors[keyof UpdateStudentErrors];

export type UpdateStudentResponses = {
    /**
     * Successful Response
     */
    200: StudentRead;
};

export type UpdateStudentResponse = UpdateStudentResponses[keyof UpdateStudentResponses];

export type SearchSubjectByNameData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Query
         */
        query: unknown;
    };
    url: '/api/v1/subject/search';
};

export type SearchSubjectByNameErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchSubjectByNameError = SearchSubjectByNameErrors[keyof SearchSubjectByNameErrors];

export type SearchSubjectByNameResponses = {
    /**
     * Response Search Subject By Name Api V1 Subject Search Get
     *
     * Successful Response
     */
    200: Array<SubjectRead>;
};

export type SearchSubjectByNameResponse = SearchSubjectByNameResponses[keyof SearchSubjectByNameResponses];

export type GetAllSubjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/subject/';
};

export type GetAllSubjectsResponses = {
    /**
     * Response Get All Subjects Api V1 Subject  Get
     *
     * Successful Response
     */
    200: Array<SubjectRead>;
};

export type GetAllSubjectsResponse = GetAllSubjectsResponses[keyof GetAllSubjectsResponses];

export type CreateSubjectData = {
    body: SubjectCreate;
    path?: never;
    query?: never;
    url: '/api/v1/subject/';
};

export type CreateSubjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSubjectError = CreateSubjectErrors[keyof CreateSubjectErrors];

export type CreateSubjectResponses = {
    /**
     * Successful Response
     */
    201: SubjectRead;
};

export type CreateSubjectResponse = CreateSubjectResponses[keyof CreateSubjectResponses];

export type DeleteSubjectData = {
    body?: never;
    path: {
        /**
         * Subject Id
         */
        subject_id: number;
    };
    query?: never;
    url: '/api/v1/subject/{subject_id}';
};

export type DeleteSubjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSubjectError = DeleteSubjectErrors[keyof DeleteSubjectErrors];

export type DeleteSubjectResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteSubjectResponse = DeleteSubjectResponses[keyof DeleteSubjectResponses];

export type GetSubjectByIdData = {
    body?: never;
    path: {
        /**
         * Subject Id
         */
        subject_id: number;
    };
    query?: never;
    url: '/api/v1/subject/{subject_id}';
};

export type GetSubjectByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSubjectByIdError = GetSubjectByIdErrors[keyof GetSubjectByIdErrors];

export type GetSubjectByIdResponses = {
    /**
     * Successful Response
     */
    200: SubjectRead;
};

export type GetSubjectByIdResponse = GetSubjectByIdResponses[keyof GetSubjectByIdResponses];

export type UpdateSubjectData = {
    body: SubjectUpdate;
    path: {
        /**
         * Subject Id
         */
        subject_id: number;
    };
    query?: never;
    url: '/api/v1/subject/{subject_id}';
};

export type UpdateSubjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSubjectError = UpdateSubjectErrors[keyof UpdateSubjectErrors];

export type UpdateSubjectResponses = {
    /**
     * Successful Response
     */
    200: SubjectRead;
};

export type UpdateSubjectResponse = UpdateSubjectResponses[keyof UpdateSubjectResponses];

export type SearchTeachersByNameData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Query
         */
        query: unknown;
    };
    url: '/api/v1/teacher/search';
};

export type SearchTeachersByNameErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchTeachersByNameError = SearchTeachersByNameErrors[keyof SearchTeachersByNameErrors];

export type SearchTeachersByNameResponses = {
    /**
     * Response Search Teachers By Name Api V1 Teacher Search Get
     *
     * Successful Response
     */
    200: Array<TeacherRead>;
};

export type SearchTeachersByNameResponse = SearchTeachersByNameResponses[keyof SearchTeachersByNameResponses];

export type GetAllTeachersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/teacher/';
};

export type GetAllTeachersResponses = {
    /**
     * Response Get All Teachers Api V1 Teacher  Get
     *
     * Successful Response
     */
    200: Array<TeacherRead>;
};

export type GetAllTeachersResponse = GetAllTeachersResponses[keyof GetAllTeachersResponses];

export type CreateTeacherData = {
    body: TeacherCreate;
    path?: never;
    query?: never;
    url: '/api/v1/teacher/';
};

export type CreateTeacherErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTeacherError = CreateTeacherErrors[keyof CreateTeacherErrors];

export type CreateTeacherResponses = {
    /**
     * Successful Response
     */
    201: TeacherRead;
};

export type CreateTeacherResponse = CreateTeacherResponses[keyof CreateTeacherResponses];

export type DeleteTeacherData = {
    body?: never;
    path: {
        /**
         * Teacher Id
         */
        teacher_id: number;
    };
    query?: never;
    url: '/api/v1/teacher/{teacher_id}';
};

export type DeleteTeacherErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTeacherError = DeleteTeacherErrors[keyof DeleteTeacherErrors];

export type DeleteTeacherResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTeacherResponse = DeleteTeacherResponses[keyof DeleteTeacherResponses];

export type GetTeacherByIdData = {
    body?: never;
    path: {
        /**
         * Teacher Id
         */
        teacher_id: number;
    };
    query?: never;
    url: '/api/v1/teacher/{teacher_id}';
};

export type GetTeacherByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTeacherByIdError = GetTeacherByIdErrors[keyof GetTeacherByIdErrors];

export type GetTeacherByIdResponses = {
    /**
     * Successful Response
     */
    200: TeacherRead;
};

export type GetTeacherByIdResponse = GetTeacherByIdResponses[keyof GetTeacherByIdResponses];

export type UpdateTeacherData = {
    body: TeacherUpdate;
    path: {
        /**
         * Teacher Id
         */
        teacher_id: number;
    };
    query?: never;
    url: '/api/v1/teacher/{teacher_id}';
};

export type UpdateTeacherErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTeacherError = UpdateTeacherErrors[keyof UpdateTeacherErrors];

export type UpdateTeacherResponses = {
    /**
     * Successful Response
     */
    200: TeacherRead;
};

export type UpdateTeacherResponse = UpdateTeacherResponses[keyof UpdateTeacherResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type HealthCheckResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
