"""full_name field teacher/student

Revision ID: 776354496c75
Revises: a92e5f08dfa7
Create Date: 2026-09-22 18:13:48.013600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776354496c75'
down_revision: Union[str, None] = 'a92e5f08dfa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('full_name', sa.String(length=301), sa.Computed("last_name || ' ' || first_name || COALESCE(' ' || middle_name, '')", persisted=True), nullable=False))
    op.alter_column('students', 'middle_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('students', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index('idx_students_full_name', 'students', ['full_name'], unique=False)
    op.add_column('teachers', sa.Column('full_name', sa.String(length=301), sa.Computed("last_name || ' ' || first_name || COALESCE(' ' || middle_name, '')", persisted=True), nullable=False))
    op.create_index('idx_teachers_full_name', 'teachers', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_teachers_full_name', table_name='teachers')
    op.drop_column('teachers', 'full_name')
    op.drop_index('idx_students_full_name', table_name='students')
    op.alter_column('students', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('students', 'middle_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('students', 'full_name')
    # ### end Alembic commands ###
